"""A workaround to check if ANDROID_NDK_HOME is set."""

def _check_android_ndk_env_impl(ctx):
    # .bzl file contains ANDROID_NDK_HOME_IS_SET = True if ANDROID_NDK_HOME is set.
    content = "# Generated by check_android_ndk_env.bzl\n"
    content += "ANDROID_NDK_HOME_IS_SET = "
    content += "False" if ctx.getenv("ANDROID_NDK_HOME") == None else "True"
    content += "\n"
    ctx.file("current_android_ndk_env.bzl", content = content)

    # Dummy BUILD file to make the repository is valid.
    ctx.file("BUILD", content = "")

check_android_ndk_env = repository_rule(
    implementation = _check_android_ndk_env_impl,
    local = True,
    environ = ["ANDROID_NDK_HOME"],
)
