name: "CI-Mac"
on:
  push:
    branches:
    - main
    tags:
    - v*.*.*
  pull_request:
    branches:
    - main
  schedule:
    - cron: "0 10 * * *"  # Run at 2am PST (10am UTC) every day to refresh the cache.
  workflow_dispatch:  # Manual trigger
    inputs:
      REFRESH_CACHE:
        description: 'Refresh cache to remove unused files'
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  presubmit:
    name: "Presubmit-Mac"
    runs-on: macos-latest
    permissions:
      contents: write  # For gh release upload.
    env:
      GH_TOKEN: ${{ github.token }}  # For gh release upload.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore bazel cache
        if: >  # Restore cache only when it's not triggered to refresh the cache.
          ! (github.event_name == 'schedule' ||
             (github.event_name == 'workflow_dispatch' && inputs.REFRESH_CACHE))
        uses: actions/cache/restore@v4
        id: bazel-cache
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazel-macos
            ~/.cache/bazel-ios
          key: ${{ github.workflow }}-${{ hashFiles('**/WORKSPACE', '**/.bazelrc') }}-${{ hashFiles('**/BUILD*') }}-{{ github.sha }}
          restore-keys: |
            ${{ github.workflow }}-${{ hashFiles('**/WORKSPACE', '**/.bazelrc') }}-${{ hashFiles('**/BUILD*') }}-
            ${{ github.workflow }}-${{ hashFiles('**/WORKSPACE', '**/.bazelrc') }}-
            ${{ github.workflow }}-

      - name: Check cache hit
        run: |
          echo "Cache Hit: ${{ steps.bazel-cache.outputs.cache-hit }}"
          echo "Cache Primary Key: ${{ steps.bazel-cache.outputs.cache-primary-key }}"
          echo "Cache Matched Key: ${{ steps.bazel-cache.outputs.cache-matched-key }}"

      - name: Run bazel build on MacOS
        run: |
          bazel build --disk_cache=~/.cache/bazel-macos //...

      - name: Update litert_lm_main prebuilt for MacOS if new version tag is pushed.
        if: github.ref_type == 'tag'
        run: |
          cp bazel-bin/runtime/engine/litert_lm_main litert_lm_main.macos_arm64
          gh release upload ${{ github.ref_name }} litert_lm_main.macos_arm64 --clobber

      - name: Run bazel test on MacOS
        run: |
          bazel test --disk_cache=~/.cache/bazel-macos --test_output=errors //...

      - name: Run bazel build for iOS Simulator
        run: |
          bazel build --disk_cache=~/.cache/bazel-ios --config=ios_sim_arm64 //...

      - name: Update litert_lm_main prebuilt for iOS Simulatorif new version tag is pushed.
        if: github.ref_type == 'tag'
        run: |
          cp bazel-bin/runtime/engine/litert_lm_main litert_lm_main.ios_sim_arm64
          gh release upload ${{ github.ref_name }} litert_lm_main.ios_sim_arm64 --clobber

      - name: Save bazel cache if it's new and not triggered by pull request.
        uses: actions/cache/save@v4
        if: steps.bazel-cache.outputs.cache-hit != 'true' && github.event_name != 'pull_request'
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazel-macos
            ~/.cache/bazel-ios
          key: ${{ github.workflow }}-${{ hashFiles('**/WORKSPACE', '**/.bazelrc') }}-${{ hashFiles('**/BUILD*') }}-{{ github.sha }}
